using System;
using System.IO;
using System.Drawing;

namespace EmulationCoordination.Utilities 
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    internal class ConsoleImages 
    {
        private static Bitmap LoadImage(string imageName)
        {
            string path = Path.Combine(FileUtilities.ExecutingDirectory,"Resources",imageName);
            return (System.Drawing.Bitmap)System.Drawing.Bitmap.FromFile(path);
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GameBoy {
            get {
                return LoadImage("Gameboy.png");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GameBoyAdvance {
            get {
                return LoadImage("GameBoyAdvance.jpg");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GameBoyColor {
            get {
                return LoadImage("GameBoyColor.png");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gamecube {
            get {
                return LoadImage("gamecube.jpeg");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap N64 {
            get {
                return LoadImage("N64.png");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NES {
            get {
                return LoadImage("NES.png");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PS2 {
            get {
                return LoadImage("PS2.png");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PS3 {
            get {
                return LoadImage("PS3.png");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SegaMasterSystem {
            get {
                return LoadImage("SegaMasterSystem.png");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SNES {
            get {
                return LoadImage("SNES.png");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnknownConsole {
            get {
                return LoadImage("UnknownConsole.bmp");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wii {
            get {
                return LoadImage("Wii.bmp");
            }
        }
    }
}
